In [1]:
import pandas as pd
df=pd.read_excel("C:/Users/Abhinav/downloads/day_wise_aqi_data.xlsx")
df.head()

,date,state,area,number_of_monitoring_stations,prominent_pollutants,aqi_value,air_quality_status,unit
0,2025-06-19,Uttar Pradesh,Agra,5.0,"O3,PM2.5,PM10",49,Good,number_of_monitoring_stations in Absolute Numb...
1,2025-06-19,Karnataka,Bagalkot,1.0,PM10,46,Good,number_of_monitoring_stations in Absolute Numb...
2,2025-06-19,Maharashtra,Akola,1.0,PM10,26,Good,number_of_monitoring_stations in Absolute Numb...
3,2025-06-19,Rajasthan,Alwar,1.0,CO,76,Satisfactory,number_of_monitoring_stations in Absolute Numb...
4,2025-06-19,Andhra Pradesh,Amaravati,1.0,PM10,66,Satisfactory,number_of_monitoring_stations in Absolute Numb...

In [2]:
df.isnull().sum()

date                               0
state                              0
area                               0
number_of_monitoring_stations    141
prominent_pollutants               0
aqi_value                          0
air_quality_status                 0
unit                               0
dtype: int64

In [3]:
df["number_of_monitoring_stations"]=df["number_of_monitoring_stations"].fillna(0)

In [4]:
df.isnull().sum()

date                             0
state                            0
area                             0
number_of_monitoring_stations    0
prominent_pollutants             0
aqi_value                        0
air_quality_status               0
unit                             0
dtype: int64

In [5]:
df["date"]=pd.to_datetime(df["date"])
df["aqi_value"]=pd.to_numeric(df["aqi_value"])

In [6]:
df.groupby("area")["aqi_value"].mean().sort_values(ascending=False)

area
Loni Ghaziabad    336.500000
Jharsuguda        282.000000
Gurgaon           222.650834
Delhi             215.895080
Ghaziabad         213.321598
                     ...
Thanjavur          43.802030
Palkalaiperur      42.545126
Madikeri           41.441509
Perundurai         32.142857
Tirunelveli        31.977444
Name: aqi_value, Length: 295, dtype: float64

In [7]:
df["air_quality_status"].value_counts()

air_quality_status
Satisfactory    155222
Moderate        138532
Good             69754
Poor             43812
Very Poor        15392
Severe            2567
Name: count, dtype: int64

In [8]:
df["prominent_pollutants"].value_counts()

prominent_pollutants
PM10                 186786
PM2.5                120095
O3                    31207
CO                    24963
PM2.5,PM10            21562
NO2                    6386
PM10,O3                6259
SO2                    5363
PM2.5,O3               4985
PM10,CO                4181
O3,PM2.5,PM10          2052
PM10,NO2               1603
PM2.5,PM10,CO          1576
PM10,O3,CO              984
CO,O3                   981
PM10,SO2                729
PM10,PM2.5,NO2          720
PM2.5,NO2               704
NO2,PM10,CO             454
PM10,NO2,O3             400
PM10,PM2.5,O3           389
CO,NO2                  376
PM2.5,CO,O3             374
PM2.5,SO2               318
NO2,O3                  209
CO,SO2                  206
PM10,CO,SO2             163
PM10,PM2.5,SO2          152
PM2.5,CO,NO2            136
SO2,O3                  135
PM10,CO,O3              121
PM10,SO2,O3             107
NH3                     100
NO2,CO,O3                97
PM10,NO2,PM2.5,O3        83
PM2.5,CO,SO2             56
PM2.5,SO2,O3             40
PM10,NO2,SO3             38
NO2,SO2                  37
SO3,CO,O3                36
NO2,SO2,CO               28
PM2.5,NO2,SO2            20
PM2.5,NO2,O3             16
CO,NO2,O3                12
NO2,O3,SO2                9
PM2.5,NH3                 6
PM10,NH3                  4
PM10,NH3,O3               3
PM10,NH3,CO               3
CO,O3,SO2                 3
NH3,CO,O3                 2
PM2.5,NH3,O3              2
O3,SO2                    2
O3,NH3                    1
PM2.5,NH3,CO              1
NH3,NO2,O3                1
NH3,NO2                   1
NH3,O3                    1
PM2.5,O3,SO2              1
Name: count, dtype: int64

In [9]:
df.to_csv("cleaned_aqi_data.csv",index=False)

In [10]:
import sqlite3
conn=sqlite3.connect("aqi_database.db")
df.to_sql("aqi_data",conn,if_exists="replace",index=False)

425279

In [11]:
query="""
Select state,AVG(aqi_value) AS avg_aqi from aqi_data group by state order by avg_aqi DESC;
"""
result=pd.read_sql_query(query,conn)
result.head()

              state     avg_aqi
0             Delhi  215.895080
1             Bihar  165.905256
2  Himachal Pradesh  160.133040
3     Uttar Pradesh  159.542288
4           Haryana  151.533731

In [12]:
query2="""
select area,MAX(aqi_value) as max_aqi from aqi_data group by area order by max_aqi desc limit 10;
"""
result2=pd.read_sql_query(query2,conn)
result2.head()

            area  max_aqi
0  Visakhapatnam      500
1     Vijayawada      500
2       Varanasi      500
3         Ujjain      500
4          Udupi      500

In [13]:
query3="""
select air_quality_status,count(*) as total from aqi_data
group by air_quality_status;
"""
result3=pd.read_sql_query(query3,conn)
result3.head()

  air_quality_status   total
0               Good   69754
1           Moderate  138532
2               Poor   43812
3       Satisfactory  155222
4             Severe    2567

In [14]:
query4="""
select prominent_pollutants,count(*) as occurences from aqi_data group by prominent_pollutants order by occurences desc;
"""
result4=pd.read_sql_query(query4,conn)
result4.head()

  prominent_pollutants  occurences
0                 PM10      186786
1                PM2.5      120095
2                   O3       31207
3                   CO       24963
4           PM2.5,PM10       21562

In [32]:
query5="""
select state, SUM(number_of_monitoring_stations) from aqi_data group by state order by sum(number_of_monitoring_stations) desc;
"""
result5=pd.read_sql_query(query5,conn)
result5.head()

           state  SUM(number_of_monitoring_stations)
0    Maharashtra                            101589.0
1  Uttar Pradesh                             98282.0
2          Delhi                             95750.0
3      Karnataka                             61788.0
4        Haryana                             58942.0